# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc34d9802182fb5426c2860321dbf92f14a9ed9c17b828afbdcbba5fbbc52822bc6fe54a1694bdfd2de4089cdfd4cb697210e57a4c105ca42c6c9521acd67b03

test:
  secret_key_base: 2400c34ccdf6c3e795933df96f06c2618e8e12dfc5b0a8f69ffdaf3a86e7ad7c28658544bf8d1b0f52ccc1848382f19d8d57e9cb04301663f40827279b0a7c36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
